### ISSUE TITLE
[Suggestion]please add a favorite mobs section

### ISSUE THREAD

**Issue by ImUnlimited** [ToCraft/Remorphed#13]
please add a favorite mobs thing or at least a way to organize the mobs.

I actually find myself losing more time searching for the mob that I want then actually using the mob's utility.

Sometimes I have a lot of mobs and I just wanted to favorite them so they show up first in the menu;
If you can, try to code a way to sort them by mod, name etc. but please, make so we can favorite the useful mobs.

Example:
![aaa](https://github.com/ToCraft/Remorphed/assets/69334760/040220a7-b13a-4c80-a531-c6d98a670534)

**Comment by ToCraft** [comment]
You will be glad to hear that I've already implemented favourites. :D
(I implemented it as of 75a615b78a0e31d50efff2c485de3f063536df15 )
It will be available with the next update.
