### ISSUE TITLE
(Question.)  Tropical Fish.

### ISSUE THREAD

**Issue by Malwarechubb** [ToCraft/Remorphed#14]
Why Do Tropical Fish Have No Color? Not "No Color." But They Are Just White With Gray Markings.

**Comment by ToCraft** [comment]
Yeah, that's since there are way to many possible combinations for tropical fish. I tested it and Remorphed literaly got stuck since it took to long to render all those variants in the menu.
I can change it, so you don't have the default colors but rather random ones.

**Comment by Natedogwoooof** [comment]
> Yeah, that's since there are way to many possible combinations for tropical fish. I tested it and Remorphed literaly got stuck since it took to long to render all those variants in the menu. I can change it, so you don't have the default colors but rather random ones.

Can you do the same thing with villagers?

**Comment by ToCraft** [comment]
> Can you do the same thing with villagers?

What about it chooses them random, but based on your UUID? This way, you won't be a completely different villager/fish each time you transform.

**Comment by Malwarechubb** [comment]
That's a good idea. Hope you add it during the next update.

**Comment by Natedogwoooof** [comment]
> > Can you do the same thing with villagers?
> 
> Yeah, I can, but I don't think you want to be a different villager each time you transform into one. But, what if e.g. the colors are chosen randomly but based on your UUID? This way, you won't be a completely different villager/fish each time you transform.

Player uuid? I don't really like that idea unless there's a way to change it in a game on single player

**Comment by ToCraft** [comment]
> Player uuid? I don't really like that idea unless there's a way to change it in a game on single player

And if there'd be a config option to switch between randomly selected on world join (and then persistent) and each time you transform randomly selected?
