### ISSUE TITLE
Game Crashed

### ISSUE THREAD

**Issue by Natedogwoooof** [ToCraft/Remorphed#16]
### Mod loader

Fabric

### Minecraft version

1.20.4

### Remorphed version

2.0 dev

### Woodwalkers version

2.1 dev

### CraftedCore version

2.1 dev

### Modloader version

0.15.7

### The latest.log file

https://gist.github.com/Natedogwoooof/c129acc08b8cbb2afb085ad9e2762187

### Issue description

game crashes in the middle of loading

### Other

https://gist.github.com/Natedogwoooof/0eb015ae1588a7c77fa4facc02afa98b crash log

**Comment by ToCraft** [comment]
Yeah, I'm aware that the dev-version of woodwalkers isn't compatible with Remorphed yet. (I fixed a typo in the config file and exactly the same config option is used by Remorphed). It will be fixed with the next release.

**Comment by Natedogwoooof** [comment]
ok
