### ISSUE TITLE
MC Forge 1.20.1 Morph Select Menu Crashing on Attempting to Open

### ISSUE THREAD

**Issue by Fearxghost** [ToCraft/Remorphed#17]
### Mod loader

Forge

### Minecraft version

1.20.1

### Remorphed version

remorphed-2.0-forge.jar

### Woodwalkers version

walkers-2.1-forge.jar

### CraftedCore version

craftedcore-2.1-forge.jar

### Modloader version

Forge - 47.2.0

### The latest.log file

https://gist.github.com/Fearxghost/b496eca09352eba047542ccce39e72ef

### Issue description

Game crash on attempt to open morph menu

### Steps to reproduce

1. Start game 2. attempt to open menu of slain mobs available for morphing

### Other

Remorphed is one of many mods loaded with this pack possibility of mod conflict.

**Comment by ToCraft** [comment]
Yeah, it looks like an incompatibility with Gigeresque. I don't know when I'll be able to fix it, but I'll do my best.

**Comment by ToCraft** [comment]
Alright, I just tested it with Forge and it worked. Could it be possible that it's an issue of Sinytra Connector?
You can try to use to forge versions of those mods. Feel free to reach out to me if it still crashes.

```
	Sinytra Connector: 1.0.0-beta.36+1.20.1
		SINYTRA CONNECTOR IS PRESENT!
		Please verify issues are not caused by Connector before reporting them to mod authors. If you're unsure, file a report on Connector's issue tracker.
		Connector's issue tracker can be found at https://github.com/Sinytra/Connector/issues.
		Installed Fabric mods:
		| ================================================== | ============================== | ============================== | ==================== |
		| gigeresque-connector-1.20.1-0.5.62$better-crawling | MixinExtras                    | com_github_llamalad7_mixinextr | 0.2.0-rc.3           |
		| gigeresque-connector-1.20.1-0.5.62_mapped_srg_1.20 | Gigeresque                     | gigeresque                     | 0.5.62               |
		| gigeresque-connector-1.20.1-0.5.62$better-crawling | Better Crawling                | bettercrawling                 | 1.0.4                |
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
```
