### ISSUE TITLE
1.20.1 Crashing on startup of minecraft

### ISSUE THREAD

**Issue by FryFritters** [ToCraft/Remorphed#18]
### Mod loader

Forge

### Minecraft version

1.20.1

### Remorphed version

2.0

### Woodwalkers version

2.1

### CraftedCore version

2.1

### Modloader version

47.2.20

### The latest.log file

The game literally crashes on startup

### Issue description

Essentially Minecraft keeps crashing on launch with the remorphed mod installed.

### Steps to reproduce

1. Start Le game with mod(s) installed
2. [Insert crash]

**Comment by ToCraft** [comment]
You forgot to attach a log file. I can't reproduce the crash if I don't know what other mods you installed and if you're running the correct java.
