### ISSUE TITLE
MC Forge 1.20.1 Morph Select Menu Crashing on Attempting to Open bug.. The version I use is 1.20.1-forge-47.2.0

### ISSUE THREAD

**Issue by KralOyuncu55** [ToCraft/Remorphed#19]
### Mod loader

Forge

### Minecraft version

1.20.1-forge-47.2.0

### Remorphed version

1.20.1-forge-3.1

### Woodwalkers version

1.20.1-forge-3.0

### CraftedCore version

1.20.1-forge-3.0

### Modloader version

1.20.1-forge-47.2.0

### The latest.log file

https://gist.github.com/KralOyuncu55/ee00e30ecdeaa3ef5fdd20915f9607a0

### Issue description

First of all, hello. The problem I'm having is when I press the Remorphed key, the game crashes in a way I don't understand and gives an error. I got this error even though I downloaded the latest version of everything. I had no problems entering the game. I opened a new world but it keeps giving errors. When I killed a creature in Identity mode, it would die and enter me in a black form, but there is no such thing in this mode or it did not happen to me.

### Steps to reproduce

1.I installed the latest mods.
2.I opened the game
3.I entered my new world
4.I pressed the button
5.I was kicked out of the game and it gave an error

### Other

I think Remorphed but it could be something else.

**Comment by ToCraft** [comment]
Probably mod incompatibility. I don't know, when I find the time to fix it.

**Comment by ToCraft** [comment]
It _should_ be fixed as of 3.2. If not, feel free to reopen this issue.
