### ISSUE TITLE
Game Crash on start.

### ISSUE THREAD

**Issue by Flickderp** [ToCraft/Remorphed#20]
### Mod loader

Forge

### Minecraft version

1.20.1

### Remorphed version

1.20.1 Forge 3.1

### Woodwalkers version

1.20.1-forge-3.0

### CraftedCore version

 1.20.1-forge-3.0

### Modloader version

48.2.0

### The latest.log file

unknown.

### Issue description

Im unable to open minecraft with the Mod active.

### Steps to reproduce

Simply try to start minecraft via the launcher.

### Other

I have the Jujutsu craft mod active along with all required mods to use with it.

**Comment by ToCraft** [comment]
What do you mean with "the latest.log file is unknown"?

**Comment by ToCraft** [comment]
I've tested it and everything worked perfectly.
![image](https://github.com/ToCraft/Remorphed/assets/38883321/f8ff379b-5e13-429f-8c0c-a36391b6e9d3)

![image](https://github.com/ToCraft/Remorphed/assets/38883321/728f0b4b-c181-4496-9682-94bf926b7822)
