### ISSUE TITLE
Crash on opening morph menu

### ISSUE THREAD

**Issue by katubug** [ToCraft/Remorphed#21]
### Mod loader

Forge

### Minecraft version

1.20.1

### Remorphed version

3.2

### Woodwalkers version

3.1

### CraftedCore version

3.1

### Modloader version

47.2.20

### The latest.log file

https://gist.github.com/katubug/057779fac6714362bcb22d52d1bc018a

### Issue description

When accessing the morph menu, the game crashes. This happened to me in survival, while transformed into a pig.

### Steps to reproduce

1. Enter world
2. Attempt to access morph menu

### Other

Possibly a conflict with EMF? But the crash report seems to be unrelated to it, idk.

**Comment by KralOyuncu55** [comment]
Try Minecraft version 1.20.1 - 47.2.0 bro, I have no problems, also for your information, the recommended forg version for 1.20.1 is 47.2.0.

**Comment by katubug** [comment]
Unfortunately one of the mods I have requires 47.2.20, so that's not an
option.

**Comment by KralOyuncu55** [comment]
It should also support 47.2.0, try it because most mods are made for that.  "It doesn't hurt to try"

**Comment by katubug** [comment]
My dude, I appreciate that you want to help, but please respect that I know
what I'm talking about. The whole reason I upgraded to the 47.2.20 was
because my game failed to launch and gave the error that whatever mod it
was (this was weeks ago so I don't remember) required a higher version of
Forge.

It's possible that it's a mod conflict, and that's why it's not happening
to you. I'm hoping the developer can weigh in. Please give them the chance
to.

**Comment by KralOyuncu55** [comment]
Of course I respect it, I'm just saying, I made a lot of mistakes too, I wrote like you, I said it, don't worry, I just wrote it to help you.

**Comment by ToCraft** [comment]
Alright guys, I just went through some code. I'm not one hundret percent sure, but I think I was able to fix it as of c8099b53acbb4c52b7bda3799b1cc2c7cf2c40bd.
It was probably caused since I messed around with the background code of the menu in the latest updates (and in the upcoming one ;D ).
