### ISSUE TITLE
When i try to search for morphs game crashes

### ISSUE THREAD

**Issue by krjencik** [ToCraft/Remorphed#25]
### Mod loader

NeoForge

### Minecraft version

1.20.4

### Remorphed version

3.4

### Woodwalkers version

3.2

### CraftedCore version

3.1.2

### Modloader version

20.4.200

### The latest.log file

https://gist.github.com/krjencik/2c03ffc788f41ee9f3abe8d17f67e447

### Issue description

I tried to search for a certain morph and the game crashed.

### Steps to reproduce

1. Start game 2. open the morph menu. 3. type something into the search bar

### Other

Dont know. Maybe its incompatible with mods like aoa. (which have their own mobs).

This problem i have in creative. Dont know how its with survival...

**Comment by Natedogwoooof** [comment]
aoa

**Comment by Natedogwoooof** [comment]
that mob will need to be blacklisted

**Comment by krjencik** [comment]
by aoa i mean Advent of Ascension mod.

**Comment by ToCraft** [comment]
I think you should report to the [Authors of Advent of Ascension](https://github.com/Tslat/Advent-Of-Ascension/issues), that rendering they're Toy Merchant crashes the whole game.
(I tested it- Of course I could blacklist it, but it would still crash the game when the Toy Merchant is summoned).

**Comment by Natedogwoooof** [comment]
> by aoa i mean Advent of Ascension mod.

I know im just more of a divinerpg guy and orespawn/ chaos awakens
