### ISSUE TITLE
Whn log in, I lose all of the mobs I have unlocked except the creeper, and tropical fish.

### ISSUE THREAD

**Issue by TheEpicTen** [ToCraft/Remorphed#26]
### Mod loader

Fabric

### Minecraft version

1.20.4

### Remorphed version

3.4

### Woodwalkers version

3.2

### CraftedCore version

3.1.2

### Modloader version

0.15.7

### The latest.log file

https://gist.github.com/TheEpicTen/1a6e42e0fd21ec102f9603f3e563ffb2

### Issue description

Go into morph menu after restart game, lost all but 2 mods, but still shows as unlocked when using `/remorphed hasShape @s pig`

### Steps to reproduce

1. Join a server
2. Kill a few mobs, morph into them.
3. Restart game

**Comment by ToCraft** [comment]
Did this occur on singleplayer, too?
And: Did you restart the server, too?
(It sounds like a synchronization issue but it could be a data loading error, too.)
