### ISSUE TITLE
Option to rebind the ability hotkey

### ISSUE THREAD

**Issue by Eavilaswayce** [ToCraft/Remorphed#27]
### Describe your idea, include images if necessary

I think I've looked everywhere and don't see any option to rebind the 'R' key for using a creatures' ability. Could this be implemented please?

Thanks

**Comment by ToCraft** [comment]
You need to change it in the "Woodwalkers" section.

**Comment by Eavilaswayce** [comment]
I'm so dumb, apologies for that.
