### ISSUE TITLE
Toogle for Variants

### ISSUE THREAD

**Issue by ToCraft** [ToCraft/Remorphed#3]
The menu really should feature a toggle for variants, especially when Woodwalkers features support for MoreMobVariants & Qark....

**Comment by Natedogwoooof** [comment]
Quark?

**Comment by ToCraft** [comment]
Nvm.
I played a modpack with some friends and wondered why there were white cows and similiar stuff and they answered, this was introduced by Quark, so I wrote it down here ;D

**Comment by ToCraft** [comment]
Implemented as of d6b2d04a51cfaa265cc4a771dac51df42823b52f
