### ISSUE TITLE
[Bug] 🐞Severe FPS Drop When Swimming In Another Shape

### ISSUE THREAD

**Issue by serioos** [ToCraft/Remorphed#30]
### Mod loader

Forge

### Minecraft version

1.20.1

### Remorphed version

remorphed-3.5-forge

### Woodwalkers version

walkers-4.1-forge

### CraftedCore version

craftedcore-3.2.3-forge

### Modloader version

47.2.20

### The latest.log file

https://gist.github.com/serioos/93242ec371a5fb7aa1b342582a2c1ae2

### Issue description

I really love your Remorphed mod. Thank you so much. It worked perfectly for me on Fabric. Now I moved to Forge, and installed Remorphed again, because I like it a lot. But it doesn't seem to be working as smoothly as on Fabric.

Whenever I transform and try to swim, my FPS drops from a solid smooth 60 to 1 and 2, but when I transform back, it goes away instantly and my FPS comes back. Even flying over water in another shape causes this. I tried this all with Bee, Zombie, Phantom, and Cod shapes and they all drop FPS.

![2024-04-14_16 24 28](https://github.com/ToCraft/Remorphed/assets/93765296/abf900c1-10e2-4419-9f07-2594d2b171c7)
![2024-04-14_16 24 08](https://github.com/ToCraft/Remorphed/assets/93765296/2649eb44-5731-4f3b-9018-b31026d4c9ac)

I do not know why this happens. Could you please help me figure out what is causing this? Maybe one of the mods is conflicting with yours. Or maybe it's just a bug.

### Steps to reproduce

1. Go to water, preferably ocean. That's the worst drop in FPS.
2. Transform into another shape.
3. Try to swim around

### Other

Here's my modpack for testing:

[Mousey-5.0.zip](https://github.com/ToCraft/Remorphed/files/14970794/Mousey-5.0.zip)

**Comment by serioos** [comment]
I did a spark profile and it seems like the Man from Fog is the most resource heavy mod followed right after by WoodWalkers when I am swimming. I can remove the man from fog, but the WoodWalkers is still drawing so much unreasonable resources for some reason:

https://spark.lucko.me/REnWitlFBX

![image](https://github.com/ToCraft/Remorphed/assets/93765296/f14c5deb-4082-4f6b-a5cf-f2e920c6b9bf)

**Comment by ToCraft** [comment]
I think it's a resource leak in the skill system. I'll do my best to optimize the background progress to fix this issue.

**Comment by ToCraft** [comment]
Alright, first of all, I couldn't test your modpack (even without any of my own mods) since I had about 1-2 FPS and it crashed after 10s of playing since it was too heavy. Nevertheless, I tried to improve some logic in the skill system (as of [`79b19cc`](https://github.com/ToCraft/woodwalkers-mod/commit/79b19cc244d211d82cd5ca2bc032a5425dbd33f9)) and it should be better now, though, as I said, I can't test it in combination with your modpack.
