### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by Natedogwoooof** [ToCraft/Remorphed#31]
### Mod loader

Fabric

### Minecraft version

1.20.4

### Remorphed version

3.5 dev

### Woodwalkers version

4.1 dev

### CraftedCore version

3.2.4 beta dev

### Modloader version

0.15.10

### The latest.log file

https://gist.github.com/Natedogwoooof/9451807a2b7be6fb152763d0a0e3ad46

### Issue description

game crashes when openng morph menu, something aboult a special shape wigit

### Steps to reproduce

1. start game
2. create/ enter world
3. open morph menu

**Comment by ToCraft** [comment]
Yeah, don't use the latest walkers indev version with remorphed. I haven't adjusted remorphed yet

**Comment by Natedogwoooof** [comment]
> Yeah, don't use the latest walkers indev version with remorphed. I haven't adjusted remorphed yet

ok sorry
