### ISSUE TITLE
Newest version prevents game from starting

### ISSUE THREAD

**Issue by florian-berger** [ToCraft/Remorphed#34]
### Mod loader

Forge

### Minecraft version

1.20.1

### Remorphed version

3.6.2

### Woodwalkers version

4.4.3

### CraftedCore version

4.2.2

### Modloader version

47.2.0 (also happens with latest 47.2.32)

### The latest.log file

[latest.log](https://github.com/ToCraft/Remorphed/files/15394587/latest.log)

### Issue description

Currently, I'm creating a modpack and I really want to include the Remorphed mod.

But when I try to start the game having the mod included, loading always get stuck at the following point - as you can see, the CPU load goes down below 1% and stays there forever:
![image](https://github.com/ToCraft/Remorphed/assets/10084586/f6f3c7af-d529-4e2e-8007-62e4a2bfed90)

No matter how long I wait, it is not continuing (max. wait time I did: around 30 minutes). I have to close the window via task manager, as the button for it is not responding. When I remove the "remorphed-3.6.2-forge.jar" file from the mods folder, the game is starting without any problems.

Trying to downgrade the mod version to 3.6.1 leads to an ClassNotFoundException, so this is not working too. Do you have any idea why it behaves like it does?

### Other

Here is the list with all installed mods:
[modlist.txt](https://github.com/ToCraft/Remorphed/files/15394603/modlist.txt)

**Comment by ToCraft** [comment]
I know it's not that easy, but could you send me another list of just the mods where it crashes? If not, I can go through your list and weed out all the mods that are definitely not the cause in order to debug the problem, but I don't have the time right now and it might take a while.

**Comment by ToCraft** [comment]
I've literally reworked most things in CraftedCore 5. It's likely the issue won't occur anymore. (Please reopen in case I'm wrong).
