### ISSUE TITLE
Can't seem to turn back into a human

### ISSUE THREAD

**Issue by katubug** [ToCraft/Remorphed#35]
### Mod loader

Forge

### Minecraft version

1.20.1

### Remorphed version

3.6.2

### Woodwalkers version

4.4.3

### CraftedCore version

4.2.3

### Modloader version

47.2.30

### The latest.log file

[latest.log](https://github.com/ToCraft/Remorphed/files/15448992/latest.log)

### Issue description

I am transformed in my creative world, but I cannot transform back into a human, either via the Woodwalkers menu or the Remorphed menu.

### Steps to reproduce

1. Start game
2. Transform into a mob
3. Attempt to transform back

**Comment by ToCraft** [comment]
fixed as of 8871db653484b88c5d4beedcb230994dd243221f

**Comment by katubug** [comment]
Hi, sorry to bother - is this going to be on Curseforge soon? Just eager to update my pack so I am no longer a cow :3

**Comment by ToCraft** [comment]
Yeah, I sill got to do some small adjustments before the release, but it's foing to be wjthin the next few days
