### ISSUE TITLE
[1.21 Fabric Server] remorphed:favorite_sync Packet encoding fail

### ISSUE THREAD

**Issue by NotPhoenic** [ToCraft/Remorphed#41]
### Mod loader

Fabric

### Minecraft version

1.21

### Remorphed version

4.0

### Woodwalkers version

5

### CraftedCore version

5.3

### Modloader version

0.15.11

### The latest.log file

Client: https://mclo.gs/wKLLHsJ
Server: https://mclo.gs/NxVjqa5

### Issue description

Unable to join server after adding Remorphed 4.0 and other ToCraft mods, see disconnect message in attached screenshot or in logs.

### Steps to reproduce

1. Create a fabric 1.21(0.15.11) server

2. Add the following mods:
craftedcore-5.3
fabric-api-0.102.0+1.21
remorphed-4.0
skinshifter-1.1.jar
walkers-5-fabric.jar

3. Attempt to join
4. Get the following error
![image](https://github.com/user-attachments/assets/ccca9c18-6325-4903-94cd-97be92fa0ed5)

### Other

Works completely fine in singleplayer

**Comment by ToCraft** [comment]
Alright, I found the error. I'll probably upload a fix today or tomorrow.

**Comment by ToCraft** [comment]
fixed as of 6c5b0384c071de0d22e7ffc047cfb9febda1df9c
