### ISSUE TITLE
Cannot morph into boss mobs (wither & ender dragon) while in survival mode.

### ISSUE THREAD

**Issue by StarGazerBoi01134** [ToCraft/Remorphed#45]
### Mod loader

Forge

### Minecraft version

1.20.1

### Remorphed version

4.1

### Woodwalkers version

5.2

### CraftedCore version

5.5

### Modloader version

47.3.0

### The latest.log file

[latest.log](https://github.com/user-attachments/files/16912668/latest.log)

### Issue description

After killing the wither or the ender dragon, there is no option to transform into those mobs in survival mode. Creative mode works just fine, but there is no option while in survival.

### Steps to reproduce

1. Be in survival mode.
2. Kill Wither or Ender Dragon.
3. Open morph screen.
4. See that the Wither and the Ender Dragon are not options.

**Comment by ToCraft** [comment]
Since the boss mobs are very powerful you have to kill them twice. You can change it in the config file.
