### ISSUE TITLE
Two Things

### ISSUE THREAD

**Issue by SirPeteThe1st** [ToCraft/Remorphed#48]
### Describe your idea, include images if necessary

In previous morph mods, I was able to acquire the abilities of certain mobs, including their special attacks like Ghast's fire ball and Blaze's fire shot. I can only do the basics in this mod.
Also, I would use the morphs as a disguise to not get attacked by hostile mobs. This doesn't seem to be the case here either. 
Please advise.

**Comment by ToCraft** [comment]
You can already shoot Fireballs as a Ghast. Take a look at the [wiki](https://github.com/ToCraft/woodwalkers-mod/wiki/Abilities) for details. Moreover, hostile mobs attack you if they "see" how you morphed. Try morphing into a zombie, and then going near another one. As long as you don't try to interact with another hostile mob, they'll stay neutral. To disable that you can trigger them, set [`playerCanTriggerHostiles` in the `walkers.json5`](https://github.com/ToCraft/woodwalkers-mod/wiki/Configuration#playercantriggerhostiles) to `false`.
