### ISSUE TITLE
Cannot access menus, Cannot transform

### ISSUE THREAD

**Issue by LemonieSnickers** [ToCraft/Remorphed#50]
### Mod loader

Forge

### Minecraft version

1.20.1

### Remorphed version

4.2

### Woodwalkers version

5.4

### CraftedCore version

5.5

### Modloader version

47.3.0

### The latest.log file

[latest.log](https://github.com/user-attachments/files/17692304/latest.log)

### Issue description

I can scan entities and see the tingle message, but I do not transform, and no matter how I set the key binds I cannot access any menus

### Steps to reproduce

Scan entity
Try access menus

**Comment by LemonieSnickers** [comment]
> You only can scan entities if you're using woodwalkers without ReMorphed. Is ReMorphed listed in your in game mod list?

Yes, So I tried with both, remorphed no matter what I kill I cannot transform, and Woodwalkers the scan won't turn me, and for both no matter the keybind I can't open the menu

**Comment by ToCraft** [comment]
Alright, I just installed every mod you installed and everything worked. Please ensure you pressed the right button to open the menu and maybe try it in another world, it might be that your level data corrupted.

**Comment by ToCraft** [comment]
closed due to inactivity
