### ISSUE TITLE
my mod working but i didnt able to see mobs i am seeing my character instead of mobs

### ISSUE THREAD

**Issue by Rakshit-sys** [ToCraft/Remorphed#52]
### Mod loader

Forge

### Minecraft version

1.20.1

### Remorphed version

4.2

### Woodwalkers version

5.4

### CraftedCore version

5.5

### Modloader version

..14.23

### The latest.log file

[latest.log](https://github.com/user-attachments/files/17968935/latest.log)

### Issue description

please help me tell why i still get issue

### Steps to reproduce

help me
[latest.log](https://github.com/user-attachments/files/17968936/latest.log)

### Other

help meeee
[latest.log](https://github.com/user-attachments/files/17968937/latest.log)

**Comment by ToCraft** [comment]
Please provide a more detailed issue description. Furthermore, please further limit the error by sorting out mods that do not affect the error.

**Comment by ToCraft** [comment]
Closed due to lack of response. Will be reopened upon response
