### ISSUE TITLE
The GUI for hunger and armor disappears whenever I morph

### ISSUE THREAD

**Issue by ArtBotReal** [ToCraft/Remorphed#53]
### Mod loader

Forge

### Minecraft version

1.20.1

### Remorphed version

4.2

### Woodwalkers version

5.4

### CraftedCore version

5.6

### Modloader version

0.16.9

### The latest.log file

[latest.log](https://github.com/user-attachments/files/18052790/latest.log)

### Issue description

Whenever I morph into a blaze, the hunger and armor part of my GUI disappear. I tried removing other modded GUI components like the Dehydration and EnvironmentZ, but it still did not change at all. I assume that these mods might alter the Remorphed mod, but it didn't. Other mods I have could have an effect as I have around 500 mods installed. Sample image attached.
![image](https://github.com/user-attachments/assets/8d38e80c-6cbc-486d-9783-247dfa4a429e)

### Steps to reproduce

1. Start game and enter a creative world.
2. Morph into a blaze
3. Go to survival and see result

**Comment by ToCraft** [comment]
That's actually intented. Take a look at the [AttackForHealthTrait](https://github.com/ToCraft/woodwalkers-mod/wiki/Traits#attackforhealthtrait) for detail.
