### ISSUE TITLE
Feature Request: kill hostiles to get their form, scan friendlies to get theirs

### ISSUE THREAD

**Issue by katubug** [ToCraft/Remorphed#6]
Hi! I love the addon you've made and I'm super excited to use it in my witchy modpack! However, I see that the option to "kill to unlock" is only a full toggle. I really like the idea of having to defeat hard foes to unlock their forms, but I feel awful that if I want to turn into a cat, I have to kill one! Is it possible to add a feature where if a creature is hostile, you must kill it, but if it's neutral or tameable, it can be scanned?

Thanks so much for your time!

**Comment by ToCraft** [comment]
That's actually a very neat idea, I'll implement it with a config option to toggle it. :D

**Comment by ToCraft** [comment]
Alright, I implemented this as of 14f49fed0602038cf9cd78a4d2ddab5bec40b165

**Comment by katubug** [comment]
Awesome, thank you so much!
