### ISSUE TITLE
Custom blacklisted mobs through Woodwalkers still appear in Remorphed selection menu

### ISSUE THREAD

**Issue by katubug** [ToCraft/Remorphed#7]
**Bug description**
Hi! I'm currently on Forge for 1.20.1, version 47.2.19. I'm using 1.1 of Remorphed and 1.12.1 of Woodwalkers.

I am trying to blacklist extra mobs using a datapack, which is loaded through KubeJS. Filepath is: `\kubejs\data\walkers\tags\entity_types\blacklisted.json`

However, they are still appearing in the menu after restarting my game:
![2024-01-12_13 17 27](https://github.com/ToCraft/Remorphed/assets/20935286/ed085e33-b5e0-4927-80d9-722e3b97525a)

I thought perhaps it was because I was in creative, but switching myself to survival also has them still showing up. Additionally, even though I'm in survival it still shows me having unlocked everything?

**Game log:**
Here is both my latest.log and the blacklisted.json file: https://gist.github.com/katubug/7967a30cf817b2696a8c1a630e165608

**Comment by katubug** [comment]
Let me know if you'd like a separate ticket for this, but I just went into a purely survival world and attempted to access the form selection, which gave me an explanatory screen. I just changed the kill setting changed to "0" from "1," because I thought that would allow me to use the U keybind (since it still shows the message from Woodwalkers). Using that keybind didn't unlock a form, so I killed a turtle and suddenly ALL forms were unlocked.

**Comment by ToCraft** [comment]
> Let me know if you'd like a separate ticket for this, but I just went into a purely survival world and attempted to access the form selection, which gave me an explanatory screen. I just changed the kill setting changed to "0" from "1," because I thought that would allow me to use the U keybind (since it still shows the message from Woodwalkers). Using that keybind didn't unlock a form, so I killed a turtle and suddenly ALL forms were unlocked.

I'll try to write something, so when you set the the kill setting to zero, you'll have everything unlocked by default (until you change the value of course).

> I thought perhaps it was because I was in creative, but switching myself to survival also has them still showing up. Additionally, even though I'm in survival it still shows me having unlocked everything?

Did you set `killToUnlock` to `0` here, too?

**Comment by katubug** [comment]
Sorry for the late reply. In my initial post, I'm pretty sure the killToUnlock was set to 1, but my memory is imperfect.

**Comment by katubug** [comment]
I can, but in my experience that means the datapack doesn't get properly
overwritten. Testing it now.

**Comment by katubug** [comment]
I changed it to "false" and it does seem to be working now! How odd, normally it doesn't work if replace isn't set to true.

**Comment by katubug** [comment]
So for the other issue, I did some testing. This is version 1.1 of Remorphed, 1.12.1 of Woodwalkers.

With "killToUnlock" set to 0, started a new creative world: had all unlocks automatically.

With "killtoUnlock" set to 0, started a new survival world: started with no unlocks. killed 1 mob and then had all unlocks.

With "killToUnlock" set to 1, started a new creative world: had all unlocks automatically.

With "killtoUnlock" set to 1, started a new survival world: started with no unlocks. killed 1 mob and had only that mob unlocked.

I'm assuming that's all working as intended? The behavior I'm hoping for is the sort I mentioned in my other ticket: I want to be able to scan friendly mobs to unlock them, and kill hostiles to unlock them. Which I think you said you've started work on, right?

**Comment by ToCraft** [comment]
Actually, I already implemented it, but I still got some stuff to do in the Woodwalkers-mod, but once I published the newest woodwalkers-version, I'm going to publish the newest dev version of Remorphed, too (to avoid incompatibility).
