### ISSUE TITLE
Make it easyer to morph into player

### ISSUE THREAD

**Issue by Natedogwoooof** [ToCraft/Remorphed#8]
so in identity i don't have a problem but someone else said they did but so in the corner there was a Steve head that morphed you back into yourself, also when you morphed into something there would be a yellow boarder for what you morphed into

**Comment by ToCraft** [comment]
Yeah, maybe I'll add some kind of box. I removed the steve head since there's the "Display Variants" button now, but if you have an idea where I should place it instead, let me know :D

**Comment by JaisDK** [comment]
How do yo morph back into the player model since the button is gone? the variants button doesn't do anything

**Comment by ToCraft** [comment]
Alright, I just implemented your ideas as of 591d126d7f2c991ae24cc3662a6c296eeca01221 and ea573da15ba4fad0ab34d1b28b0e3135d72e6a76. Please note that now there isn't Steve's head, but the one of the current player! :D
